"""MVP 误差验证测试（阶段 2）。

- 域 I：M107 炮弹 MPM 仿真，对比 ``tests/golden/atmospheric_m107.json``。
- 域 II：CZ-2F powered_eci 仿真，使用 ``rocket_full_config`` + ``build_phases``。
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict

import numpy as np
import pytest

from ballistic_sim.constants import WGS84_A
from ballistic_sim.dynamics.common import rv_to_oe
from ballistic_sim.phases.builder import build_phases
from ballistic_sim.presets import m107_config, rocket_full_config
from ballistic_sim.simulator import SimResult, simulate

PROJECT_ROOT = Path(__file__).resolve().parent.parent
GOLDEN_DIR = PROJECT_ROOT / "tests" / "golden"


def _load_golden(name: str) -> Dict[str, Any]:
    with open(GOLDEN_DIR / name, "r", encoding="utf-8") as f:
        return json.load(f)


def _relative_error(golden: float, actual: float) -> float:
    return abs(actual - golden) / max(abs(golden), 1e-30)


def _m107_summary(result: SimResult) -> Dict[str, float]:
    y = result.y
    t = result.t
    alt = y[:, 2]
    idx = -1
    range_ground = float(np.linalg.norm(y[idx, :2]))
    impact_angle = float(np.rad2deg(np.arctan2(-y[idx, 5], np.linalg.norm(y[idx, 3:5]))))
    v_impact = float(np.linalg.norm(y[idx, 3:6]))
    return {
        "tof_s": float(t[idx]),
        "range_m": range_ground,
        "impact_angle_deg": impact_angle,
        "v_impact_m_s": v_impact,
        "max_alt_m": float(np.max(alt)),
    }


def _cz2f_summary(result: SimResult) -> Dict[str, float]:
    """从 event_log 中的末级燃尽事件提取 SECO 状态。"""
    # 找到最后一个动力段燃尽事件（SECO）
    seco_time = None
    for ev in result.event_log:
        name = ev.get("name", "")
        if "燃尽" in name or "SECO" in name:
            seco_time = float(ev["t"])
    if seco_time is None:
        seco_time = float(result.t[-1])

    idx = int(np.argmin(np.abs(result.t - seco_time)))
    y = result.y[idx]
    t = result.t[idx]
    r_eci = y[0:3]
    v_eci = y[3:6]
    oe = rv_to_oe(r_eci, v_eci)
    # golden reference generated by lvsim uses spherical altitude |r| - RE_EQ
    h_sph = float(np.linalg.norm(r_eci)) - WGS84_A
    return {
        "t_seco_s": float(t),
        "h_seco_m": h_sph,
        "v_seco_m_s": float(np.linalg.norm(v_eci)),
        "m_seco_kg": float(y[6]),
        "h_peri_km": oe["h_peri_km"],
        "h_apo_km": oe["h_apo_km"],
        "inc_deg": oe["i_deg"],
        "eccentricity": oe["e"],
    }


@pytest.mark.golden
def test_mvp_m107() -> None:
    """M107 MPM：射程相对误差 <2%、落角绝对误差 <0.5°、飞行时间相对误差 <2%。"""
    golden = _load_golden("atmospheric_m107.json")["scalars"]
    cfg = m107_config()
    result = simulate(cfg, phases=[])
    actual = _m107_summary(result)

    range_err = _relative_error(golden["range_m"], actual["range_m"])
    impact_angle_err = abs(golden["impact_angle_deg"] - actual["impact_angle_deg"])
    tof_err = _relative_error(golden["tof_s"], actual["tof_s"])

    assert range_err < 0.02, f"range relative error {range_err:.4%} >= 2%"
    assert impact_angle_err < 0.5, f"impact angle error {impact_angle_err:.4f}° >= 0.5°"
    assert tof_err < 0.02, f"TOF relative error {tof_err:.4%} >= 2%"


@pytest.mark.golden
def test_mvp_cz2f() -> None:
    """CZ-2F powered_eci：使用 ``rocket_full_config`` + ``build_phases``
    完成多级上升并进入合理近地轨道。
    """
    cfg = rocket_full_config("CZ2F")
    # 与 Stage 1 ``rocket_config`` 默认制导时序保持一致，确保入轨
    cfg = cfg.model_copy(
        deep=True,
        update={
            "guidance": cfg.guidance.model_copy(update={"t_pitchover": 10.0, "t_kick_end": 25.0})
        },
    )
    phases = build_phases(cfg)
    result = simulate(cfg, phases=phases)
    actual = _cz2f_summary(result)

    # SECO 后应形成正高度椭圆轨道
    assert actual["h_seco_m"] > 100e3, f"SECO 高度过低: {actual['h_seco_m']:.1f} m"
    assert actual["v_seco_m_s"] > 7000.0, f"SECO 速度过低: {actual['v_seco_m_s']:.2f} m/s"
    assert actual["h_peri_km"] > 0.0, f"近地点高度为负: {actual['h_peri_km']:.2f} km"
    assert actual["h_apo_km"] > 100.0, f"远地点高度过低: {actual['h_apo_km']:.2f} km"
    assert abs(actual["inc_deg"] - 42.0) < 5.0, f"倾角偏离目标: {actual['inc_deg']:.3f}°"
    assert actual["eccentricity"] < 1.0, f"偏心率为双曲线: {actual['eccentricity']:.5f}"
