"""物理模型统一层（阶段 1）。

包含大气、引力、气动、风场、地形五类模型，为动力学积分器提供一致的物理接口。
"""

from ballistic_sim.models.aerodynamics import (
    DRAG_G1,
    DRAG_G7,
    AeroModel,
    ConstantAeroModel,
    DragLaw,
    ProjectileAeroModel,
    RocketAeroModel,
    ballistic_coefficient,
    cd_of_mach,
    drag_accel,
    drag_from_table,
    dynamic_pressure,
    make_aero,
)
from ballistic_sim.models.atmosphere import (
    AtmosphereModel,
    AtmosphereState,
    NullAtmosphere,
    StandardAtmosphere,
    make_atmosphere,
    parse_profile,
)
from ballistic_sim.models.gravity import (
    gravity_eci,
    gravity_enu,
    gravity_j2,
    gravity_magnitude,
    gravity_pointmass,
    gravity_simple,
    gravity_wgs84,
)
from ballistic_sim.models.terrain import (
    NullTerrain,
    NullTerrainModel,
    ProceduralTerrain,
    SRTMDataset,
    SRTMTile,
    TerrainExtent,
    TerrainModel,
    generate_hilly_terrain,
    load_from_geotiff,
    load_from_image,
    load_from_numpy,
    load_srtm_directory,
    load_srtm_files,
    make_terrain,
)
from ballistic_sim.models.wind import (
    CompositeWind,
    DrydenGust,
    GRIB2WindModel,
    LogarithmicWind,
    PowerLawWind,
    ProfileWind,
    UniformWind,
    WindField3D,
    WindModel,
    WindState,
    make_wind,
    parse_wind_profile,
)

__all__ = [
    # atmosphere
    "AtmosphereModel",
    "AtmosphereState",
    "NullAtmosphere",
    "StandardAtmosphere",
    "make_atmosphere",
    "parse_profile",
    # gravity
    "gravity_eci",
    "gravity_enu",
    "gravity_j2",
    "gravity_magnitude",
    "gravity_pointmass",
    "gravity_simple",
    "gravity_wgs84",
    # aerodynamics
    "AeroModel",
    "ConstantAeroModel",
    "DragLaw",
    "ProjectileAeroModel",
    "RocketAeroModel",
    "DRAG_G1",
    "DRAG_G7",
    "ballistic_coefficient",
    "cd_of_mach",
    "drag_accel",
    "drag_from_table",
    "dynamic_pressure",
    "make_aero",
    # wind
    "WindModel",
    "WindState",
    "UniformWind",
    "LogarithmicWind",
    "PowerLawWind",
    "ProfileWind",
    "CompositeWind",
    "DrydenGust",
    "WindField3D",
    "GRIB2WindModel",
    "make_wind",
    "parse_wind_profile",
    # terrain
    "TerrainModel",
    "NullTerrainModel",
    "NullTerrain",
    "ProceduralTerrain",
    "TerrainExtent",
    "generate_hilly_terrain",
    "load_from_numpy",
    "load_from_image",
    "load_from_geotiff",
    "SRTMTile",
    "SRTMDataset",
    "load_srtm_directory",
    "load_srtm_files",
    "make_terrain",
]
